<a href="https://colab.research.google.com/github/hrishabhxcode/Machine-Learning/blob/main/Label_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.DataFrame({
    'color': ['green', 'red' , 'orange']

})

In [9]:
df.head()

    color
0   green
1     red
2  orange

In [8]:
encoder = LabelEncoder()
encoded = encoder.fit_transform(df['color'])

Ordinal Encoding

import pandas as pd

In [11]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df = pd.DataFrame({
    'size': ['small', 'medium', 'large' , 'small' , 'small' , 'large' , 'medium']
})

In [16]:
encoder = OrdinalEncoder(categories=[['small' , 'medium' , 'large']])
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [2.],
       [1.]])

Target Guided Encoding

In [17]:
import pandas as pd

df = pd.DataFrame({
    'city': ['New York' , 'London' , 'Paris' , 'Tokyo' , 'New York' , 'Paris'],
    'price': [200 , 150 , 300 , 250 , 150 , 300]
})

df.head()

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    150

In [19]:
mean_price = df.groupby('city')['price'].mean()

In [20]:
mean_price

city
London      150.0
New York    175.0
Paris       300.0
Tokyo       250.0
Name: price, dtype: float64

In [21]:
df['city_encoded'] = df['city'].map(mean_price)

In [22]:
df

       city  price  city_encoded
0  New York    200         175.0
1    London    150         150.0
2     Paris    300         300.0
3     Tokyo    250         250.0
4  New York    150         175.0
5     Paris    300         300.0